### ISSUE TITLE
with_prototype syntax test failures

### ISSUE THREAD

**Issue by keith-hall** [trishume/syntect#101]
I've finally had chance to investigate https://github.com/trishume/syntect/issues/59 a little bit, and found something interesting.

Let's say we have a file `testdata/Packages/ASP/HTML-ASP2.sublime-syntax` with the following contents (it's basically a cut down version of the full HTML-ASP syntax, that doesn't reference ASP itself and can serve as a(n almost minimal) complete verifiable example):

```yaml
%YAML 1.2
---
# http://www.sublimetext.com/docs/3/syntax.html
name: HTML (ASP)2
file_extensions:
  - asp2
scope: text.html.asp2
contexts:
  main:
    - include: html

  asp_punctuation_begin:
    - match: '<%'
      scope: punctuation.section.embedded.begin.asp
      push:
        - match: '(?=\S)'
          set: [close_embedded_asp, begin_embedded_asp]

  html:
    - match: ''
      set:
        - include: scope:text.html.basic
      with_prototype:
        - include: asp_punctuation_begin

  begin_embedded_asp:
    - meta_content_scope: source.asp.embedded.html
    - match: '(?=%>)'
      pop: true

  close_embedded_asp:
    - match: '%>'
      scope: punctuation.section.embedded.end.asp
      pop: true
```

and the following corresponding syntax test (`testdata/Packages/ASP/syntax_test_asp2.asp2`):

```ASP
' SYNTAX TEST "Packages/User/HTML-ASP2.sublime-syntax"
<html><% example <%
' ^^^ meta.tag.structure.any.html entity.name.tag.structure.any.html
'     ^^ punctuation.section.embedded.begin.asp
'        ^^^^^^^^^^^ source.asp.embedded.html - punctuation
```

and execute `syntest` with `RUST_BACKTRACE=1 cargo run --example syntest testdata/Packages/ASP/syntax_test_asp2.asp2 testdata/Packages/`

The output is:

```
loading syntax definitions from testdata/Packages/
Testing file testdata/Packages/ASP/syntax_test_asp2.asp2
The test file references syntax definition file: Packages/ASP/HTML-ASP2.sublime-syntax
  Assertion selector "source.asp.embedded.html - punctuation" from line 5 failed against line 2, column range 17-19 (with text "<%") has scope [<text.html.asp2>, <source.asp.embedded.html>, <punctuation.section.embedded.begin.asp>]
Ok(FailedAssertions(2, 16))
exiting with code 1
```

but in ST, if we look at the scopes, we see the `<%` which had a failure in syntect has no special scopes applied to it.
![image](https://user-images.githubusercontent.com/11882719/30061114-ca078aac-924e-11e7-8d20-64ff4cd8a35d.png)

so we can conclude that the `with_prototype` is being applied in syntect to the `begin_embedded_asp` context, but isn't in ST.  I suspect there is a general rule that the `with_prototype` shouldn't apply to nested contexts pushed by matches made in itself, if that makes sense.

i.e. estimated rough sequence of events:

- the anonymous context inside the `html` context is pushed onto the stack, with the `asp_punctuation_begin` context in the `with_prototype`
- eventually the `<%` match pattern from that context is hit, and it pushes a new anonymous context - *this context should no longer have the `asp_punctuation_begin` `with_prototype` applied to it*
- the `begin_embedded_asp` context replaces the anonymous context at the top of the stack
- because syntect is still applying the `with_prototype`, the `<%` after `example` gets matched unexpectedly/incorrectly and scoped.
