### ISSUE TITLE
included contexts should still be able to pop using backrefs

### ISSUE THREAD

**Issue by keith-hall** [trishume/syntect#104]
Now that https://github.com/trishume/syntect/issues/101 is fixed, I was able to get the ASP syntax tests to pass by changing the syntax definition to not include a `with_prototype` conflict - namely by changing [\[1\]](https://github.com/sublimehq/Packages/blob/73e105fdbb7e40230600ff07712f987d6a135cb2/ASP/ASP.sublime-syntax#L677) and [\[2\]](https://github.com/sublimehq/Packages/blob/73e105fdbb7e40230600ff07712f987d6a135cb2/ASP/ASP.sublime-syntax#L682) from `scope:text.html.asp#html` to `scope:text.html.basic`:

```
loading syntax definitions from testdata/Packages/
Testing file testdata/Packages/ASP/syntax_test_asp.asp
The test file references syntax definition file: Packages/ASP/HTML-ASP.sublime-syntax
Ok(Success(4071))
Testing file testdata/Packages/ASP/syntax_test_asp2.asp2
The test file references syntax definition file: Packages/ASP/HTML-ASP2.sublime-syntax
Ok(Success(16))
exiting with code 0
```

-----

Emboldened by that, I decided to try some more syntaxes out (https://github.com/SublimeText/PackageDev/issues/98), but found a bug. In ST, it is always possible for a match pattern that will `pop` to use back references captured from the original push pattern, regardless of whether that pattern is a direct child of the context that was pushed, or was included from it at any nesting. In syntect, it only seems to allow back references that refer to the original push pattern if the pop pattern is a direct child of the context that was pushed onto the stack.

<details><summary>In syntect, an included context trying to access the back references currently causes a panic (please expand the arrow to the left of this paragraph for the backtrace).</summary>

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/option.rs:323
stack backtrace:
   1:       0x2d4be997fa - std::sys::imp::backtrace::tracing::imp::write::h3188f035833a2635
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:       0x2d4be9c4df - std::panicking::default_hook::{{closure}}::h6385b6959a2dd25b
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:349
   3:       0x2d4be9c0de - std::panicking::default_hook::he4f3b61755d7fa95
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:365
   4:       0x2d4be9c927 - std::panicking::rust_panic_with_hook::hf00b8130f73095ec
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:553
   5:       0x2d4be9c764 - std::panicking::begin_panic::h6227f62cb2cdaeb4
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:515
   6:       0x2d4be9c6d9 - std::panicking::begin_panic_fmt::h173eadd80ae64bec
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:499
   7:       0x2d4be9c667 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:475
   8:       0x2d4bec898d - core::panicking::panic_fmt::h3b2d1e30090844ff
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:       0x2d4bec88c4 - core::panicking::panic::h2596388ccef1871c
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/panicking.rs:49
  10:       0x2d4bc27856 - <core::option::Option<T>>::unwrap::hcbcf6267c1bc19a7
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/macros.rs:21
  11:       0x2d4bca0728 - syntect::parsing::parser::ParseState::parse_next_token::h0647d274e681b640
                        at /home/keith/Documents/syntect-master/src/parsing/parser.rs:201
  12:       0x2d4bc9f74a - syntect::parsing::parser::ParseState::parse_line::h89d6548f1cea9c1e
                        at /home/keith/Documents/syntect-master/src/parsing/parser.rs:103
  13:       0x2d4bbff152 - syntest::test_file::hf2ec9e02ad06e0c2
                        at /home/keith/Documents/syntect-master/examples/syntest.rs:191
  14:       0x2d4bc00314 - syntest::recursive_walk::he846690fb982efe6
                        at /home/keith/Documents/syntect-master/examples/syntest.rs:270
  15:       0x2d4bbffde8 - syntest::main::h78e5d2a4f07ea011
                        at /home/keith/Documents/syntect-master/examples/syntest.rs:256
  16:       0x2d4bea37ba - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  17:       0x2d4be9d066 - std::rt::lang_start::h65647f6e36cffdae
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:434
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/rt.rs:57
  18:       0x2d4bc00bf2 - main
  19:     0x7fd5e385782f - __libc_start_main
  20:       0x2d4bbd8ad8 - _start
  21:                0x0 - <unknown>
```
</details>
<br />

I've managed to put a small example syntax together that exhibits this behavior:

```yaml
%YAML 1.2
---
name: Include Backref Pop Test
scope: text.includebackrefpop.syntect
contexts:
  main:
    - match: '(<)(string)\s*(>)'
      scope: meta.tag.xml
      captures:
        1: punctuation.definition.tag.begin.xml
        2: entity.name.tag.localname.xml
        3: punctuation.definition.tag.end.xml
      set:
        - meta_content_scope: meta.inside-value.string.plist
        - include: pop-tag-no-children

  pop-tag-no-children:
    - match: '(</)(\2)\s*(>)'
      scope: meta.tag.xml
      captures:
        1: punctuation.definition.tag.begin.xml
        2: entity.name.tag.localname.xml
        3: punctuation.definition.tag.end.xml
      pop: true
    # - match: '<(?!!)'
    #   scope: punctuation.definition.tag.begin.xml
    #   push: unknown-tag
    #- include: scope:text.xml

  # unknown-tag:
  #   - meta_scope: meta.tag.xml
  #   - meta_content_scope: invalid.illegal.unknown-or-unexpected-tag.plist
  #   - match: '>'
  #     scope: punctuation.definition.tag.end.xml
  #     pop: true
```

which can be used with the following syntax test:

```
# SYNTAX TEST "include_backref_pop.sublime-syntax"
<string>
</string>
# ^^^^^^ entity.name.tag.localname.xml
```

**Comment by trishume** [comment]
> I was able to get the ASP syntax tests to pass by changing the syntax definition to not include a with_prototype conflict

What do you mean by "`with_prototype` conflict"? Do you know what differing behaviour is avoided by this change? I aim for compatibility even in edge cases and would like to at least know, in case it is an easy fix.

> it is always possible for a match pattern that will pop to use back references captured from the original push pattern

shiiiiiit. If I remember correctly, I look for pops with back-references as an optimization so that I don't have to save the regions when that isn't necessary. I'll probably have to fix this to look deeper using the normal context iteration logic. I'm not sure how tricky this will be but it might be tricky.

**Comment by keith-hall** [comment]
> Do you know what differing behaviour is avoided by this change?

I've made some tests and it seems that in ST, `with_prototypes` are applied in FIFO order, but syntect appears to be applying them in LIFO order. This is why the unmodified ASP syntax definition works in ST, but in syntect the match rules from the [wrong `with_prototype`](https://github.com/sublimehq/Packages/blob/73e105fdbb7e40230600ff07712f987d6a135cb2/ASP/HTML-ASP.sublime-syntax#L43-L44) are used instead of [\[1\]](https://github.com/sublimehq/Packages/blob/73e105fdbb7e40230600ff07712f987d6a135cb2/ASP/ASP.sublime-syntax#L678-L680) and [\[2\]](https://github.com/sublimehq/Packages/blob/73e105fdbb7e40230600ff07712f987d6a135cb2/ASP/ASP.sublime-syntax#L683-L685), and thus explains why removing the nested `with_prototypes` enables it to work in syntect.

This can be observed in ST with the following syntax:

```yaml
%YAML 1.2
---
# See http://www.sublimetext.com/docs/3/syntax.html
scope: test.with_prototype
contexts:
  main:
    - match: 'hello'
      scope: string
      push: other1
      with_prototype:
        - match: 'other1?'
          scope: comment
        - match: '\d+'
          scope: constant.numeric
    - match: 'bar'
      scope: punctuation.separator
  other1:
    - match: 'world'
      scope: string
      push: other2
      with_prototype:
        - match: '(an)?other2?'
          scope: storage.type
        - match: '\d+'
          scope: keyword
        - match: 'something_else'
          scope: entity.name.prototypes
    - match: '(?=bar)'
      pop: true
  other2:
    - match: 'foo'
      scope: invalid.deprecated
      pop: true
```

the idea behind this example syntax is that it should push two contexts - both using a different `with_prototype` - onto the stack at the same time, and both `with_prototype`s try to match the same text, and scope them differently so we can see which `with_prototype` wins.

So if we have sample text `hello other 123 world other2 123 something_else another2 foo` in ST:

- none of the numbers are scoped as `keyword`.
- `other` in `other2` is scoped as `comment`
- `something_else` is scoped as expected
- `another2` is scoped as `storage.type`

This shows that the patterns from the first pushed `with_prototype` (pushed with the `other1` context) are taking precedence over the patterns from the second `with_prototype` (which was pushed together with the `other2` context), and the only way the patterns from the latter `with_prototype` get matched is if the former `with_prototype` patterns don't match at that position in the document.
