### ISSUE TITLE
Confusing build failure

### ISSUE THREAD

**Issue by cmyr** [trishume/syntect#115]
More confusing because I think I've encountered this problem before, and figured it out, but I can't now. 😕❓ 

Example of this failure here:

https://travis-ci.org/google/xi-editor/jobs/286745290#L594

in my cargo.toml:

```toml
[dependencies.syntect]
version = "1.7"
default-features = false
features = ["assets","dump-load-rs"]
```

And it looks like `IoError` is not a member of bincode's error enum (it's just `ErrorKind::Io`): https://github.com/TyOverby/bincode/blob/master/src/internal.rs#L30

So it doesn't seem like this should _ever_ compile? 

I strongly believe I'm just missing something, but really no clue what, any help appreciated @trishume.
