### ISSUE TITLE
Failing to parse some sublime-syntax files

### ISSUE THREAD

**Issue by sharkdp** [trishume/syntect#156]
I'm currently using `syntect` with a custom `SyntaxSet` which is compiled from several sources.

I have experienced a few problems with some syntax files due to errors in the regex parsing (unfortunately resulting in a `panic!`, see #98).

I'm not sure if there is something that can be done about this here, but I thought it would be good to share (will #34 change something in this respect?).

### Invalid pattern in look-behind

I downloaded an advanced Markdown syntax definition from https://github.com/jonschlinkert/sublime-markdown-extended and it results in a `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(-122, invalid pattern in look-behind)', libcore/result.rs:945:5` when using it with an input like this:

``` markdown
Test

<div>
</div>
```

I tracked the error down to this section
``` yaml
    - match: '^(?=<(p|div|h[1-6]|blockquote|pre|table|dl|ol|ul|script|noscript|form|fieldset|iframe|math|ins|del)\b)(?!.*?</\1>)'
      comment: Markdown formatting is disabled inside block-level tags.
      push:
        - meta_scope: meta.disable-markdown
        - match: (?<=^</\1>$\n)
          pop: true
        - include: scope:text.html.basic
        - include: scope:text.html.handlebars
```

and this regular expression in particular: `(?<=^</\1>$\n)`. I was able to fix the parsing-error by removing the trailing `\n` in the parens, but I'm not sure if this is the right way to go.

### Target of repeat operator is invalid

The current version of the Javascript.sublime-syntax in https://github.com/sublimehq/Packages fails with `target of repeat operator is invalid` on any JavaScript file, for example:

``` javascript
var x = 2;
```

I tracked the error down to this section
``` yaml
variables:
  identifier_start: '[_$\p{L}\p{Nl}]'
  identifier_part: '[_$\p{L}\p{Nl}\p{Mn}\p{Mc}\p{Nd}\p{Pc}\x{200C}\x{200D}]'
  identifier_break: (?!{{identifier_part}})

  identifier: '{{identifier_start}}{{identifier_part}}*{{identifier_break}}'
  constant_identifier: '[[:upper:]]{{identifier_part}}*{{identifier_break}}'
  dollar_only_identifier: '\${{identifier_break}}'
  dollar_identifier: '(\$){{identifier_part}}*{{identifier_break}}+'
  func_lookahead: '\s*(async\s+)?function{{identifier_break}}'
  arrow_func_lookahead: '\s*(async\s*)?({{identifier}}|\(([^()]|\([^()]*\))*\))\s*=>'
  either_func_lookahead: (?:{{func_lookahead}}|{{arrow_func_lookahead}})
  binding_pattern_lookahead: (?:{{identifier}}|\[|\{)
  left_expression_end_lookahead: '(?!\s*[.\[\(])'
```

and the `dollar_identifier` regex in particular. The last part of this regex is `{{identifier_break}}+` which expands to `(?!...)+`. The `+` here is superfluous and I have opened [a pull request](https://github.com/sublimehq/Packages/pull/1525) to remove it, but it would be great if `syntect` would not panic in such a case.
