### ISSUE TITLE
Java syntax highlighting wrong (JavaDoc does not end)

### ISSUE THREAD

**Issue by sharkdp** [trishume/syntect#160]
The following Java file

``` java
/**
 * test
 */
class ExampleClass {
}
```

renders correctly with `syncat` and sublimehq/Packages pinned to fa6b862 (see testdata/Packages):

![image](https://user-images.githubusercontent.com/4209276/39777798-db75b1ac-5304-11e8-8a64-b318d1acce85.png)

However, when updating sublimehq/Packages to master (currently at 0f852a3) ...

``` bash
(cd testdata/Packages; git fetch; git checkout master)
make packs
```

the docstring highlighting does not end:

![image](https://user-images.githubusercontent.com/4209276/39777746-aa904570-5304-11e8-81a6-82679809b9be.png)

I'm not sure if syntect always aims to support the current state of sublimehq/Packages, but I thought it might be worth to report this.

**Comment by Keats** [comment]
Bisecting shows it come from https://github.com/sublimehq/Packages/pull/1351
It's a rewrite of JavaDoc so not easy to pinpoint the reason, unless @keith-hall can magically figure out the issue from looking at the regexes like he seems to be able to!

Since it keeps treating the rest of the class as JavaDoc, I'm guessing some context is not popped? Related to #104 maybe?

**Comment by slimsag** [comment]
I wasted a bit of time due to not finding this issue earlier, but hopefully someone else can benefit from what I've discovered here. I've managed to boil down the JavaDoc syntax into this much smaller form which demonstrates the issue:

```yaml
%YAML 1.2
---
name: Javadoc
scope: text.html.javadoc
contexts:
  prototype:
    - match: ^(\*)
      captures:
        1: punctuation.definition.comment.javadoc

  main:
    - meta_include_prototype: false
    - match: /\*\*
      scope: comment.block.documentation.javadoc punctuation.definition.comment.begin.javadoc
      embed: contents
      embed_scope: comment.block.documentation.javadoc text.html.javadoc
      escape: \*/
      escape_captures:
        0: comment.block.documentation.javadoc punctuation.definition.comment.end.javadoc

  contents:
    - match: ''
      scope: comment.block.documentation.javadoc
```

I am using the newlines (NOT no newlines) mode with a patched version of synhtml, which produces the following output:

### Test case 1

```java
package org.joda.time.chrono;/**
**/class BasicChronology extends AssembledChronology {
}
```

![image](https://user-images.githubusercontent.com/3173176/40834205-0f707be8-6545-11e8-8b85-a83ea09a018c.png)

### Test case 2

```java
package org.joda.time.chrono;/**
*/class BasicChronology extends AssembledChronology {
}
```

![image](https://user-images.githubusercontent.com/3173176/40834248-246bf3ec-6545-11e8-89c9-a6428fc899f6.png)

---

- Both of these render identical from inside ST3, but not via synhtml (with newlines).
- The second test case (the one that fails) is using a single `*/` rather than a double `**/` to close the comment.
- Removing the `prototype` section has no visible effect in ST3, however in synhtml it appears to solve the issue so it must be related.

I didn't manage to track the issue further down than this, though, as I'm just not proficient enough in Rust or Syntect's inner workings yet.
