### ISSUE TITLE
Incorrect application of scopes in CSS output

### ISSUE THREAD

**Issue by qtfkwk** [trishume/syntect#319]
1. Working with the IR_White.tmTheme downloadable from http://tmtheme-editor.herokuapp.com/#!/editor/theme/IR_White
2. Lines 703-717 of IR_White.tmTheme have:

    ```xml
    <dict>
        <key>name</key>
        <string>Markup: Heading</string>
        <key>scope</key>
        <string>markup.heading, markup.heading entity</string>
        <key>settings</key>
        <dict>
                <key>background</key>
                <string>#632D04</string>
                <key>fontStyle</key>
                <string></string>
                <key>foreground</key>
                <string>#D95B06</string>
        </dict>
    </dict>
    ```

3. According to section 13.4 Grouping of https://macromates.com/manual/en/scope_selectors ... `markup.heading, markup.heading entity` means positives must match the `markup.heading` **and** the `markup.heading entity` scopes. Also the `markup.heading entity` scope selector means `entity` items in/under `markup.heading` items. (Right?)
4. Processing into CSS with current syntect (4.5.0) via `css_for_theme_with_class_style(&ThemeSet::get_theme("IR_White.tmTheme"), ClassStyle::Spaced)` produces the following snippet for the above.

    ```css
    .markup.heading {
      color: #d95b06;
      background-color: #632d04;
    }
    .markup.heading {
      color: #d95b06;
      background-color: #632d04;
    }
    .entity {
      color: #d95b06;
      background-color: #632d04;
    }
    ```

5. It looks like it's parsing correctly (`println!("{:#?}", theme)`:

    ```rust
        ThemeItem {
            scope: ScopeSelectors {
                selectors: [
                    ScopeSelector {
                        path: ScopeStack {
                            clear_stack: [],
                            scopes: [
                                <markup.heading>,
                            ],
                        },
                        excludes: [],
                    },
                    ScopeSelector {
                        path: ScopeStack {
                            clear_stack: [],
                            scopes: [
                                <markup.heading>,
                                <entity>,
                            ],
                        },
                        excludes: [],
                    },
                ],
            },
            style: StyleModifier {
                foreground: Some(
                    Color {
                        r: 217,
                        g: 91,
                        b: 6,
                        a: 255,
                    },
                ),
                background: Some(
                    Color {
                        r: 99,
                        g: 45,
                        b: 4,
                        a: 255,
                    },
                ),
                font_style: Some(
                    (empty),
                ),
            },
        }
    ```

6. Asserting the correct CSS should instead be:

    ```css
    .markup.heading {
      color: #d95b06;
      background-color: #632d04;
    }
    .markup.heading .entity {
      color: #d95b06;
      background-color: #632d04;
    }
    ```
