### ISSUE TITLE
"clear_scopes" restore too early on "pop"

### ISSUE THREAD

**Issue by keith-hall** [trishume/syntect#45]
Imagine the following `clear_scopes_test.sublime-syntax` file:

```yaml
%YAML 1.2
---
# See http://www.sublimetext.com/docs/3/syntax.html
name: Simple Clear Scopes Test
scope: source.example
contexts:
  main:
    - match: \'
      scope: punctuation.definition.string.begin.example
      push: single_quoted_string
  single_quoted_string:
    - meta_scope: string.quoted.single.example
    - match: 'test'
      scope: example.pushes-clear-scopes.example
      push:
        - clear_scopes: 1
        - meta_scope: example.meta-scope.after-clear-scopes.example
        - match: 'foo'
          scope: foo
          push:
            - clear_scopes: 1
            - meta_scope: example.meta-scope.cleared-previous-meta-scope.example
            - match: 'bar'
              scope: bar
              pop: true
        - match: 'test'
          scope: example.pops-clear-scopes.example
          pop: true
    - match: '\\.'
      scope: constant.character.escape.example
    - match: \'
      scope: punctuation.definition.string.end.example
      pop: true
```

and the following `syntax_test_clear_scopes.txt` file:

```
# SYNTAX TEST "clear_scopes_test.sublime-syntax"
'hellotest
# ^^^^ string.quoted.single.example - example
#     ^^^^ source.example example.meta-scope.after-clear-scopes.example example.pushes-clear-scopes.example - string
#         ^ example.meta-scope.after-clear-scopes.example - example.pushes-clear-scopes.example - string
world foo bar
# ^^^^ source.example example.meta-scope.after-clear-scopes.example - example.pushes-clear-scopes - example.meta-scope.cleared-previous-meta-scope.example - string
#     ^^^^^^^ source.example example.meta-scope.cleared-previous-meta-scope.example - example.meta-scope.after-clear-scopes.example - example.pushes-clear-scopes - string
testing123'
# ^^ example.meta-scope.after-clear-scopes.example example.pops-clear-scopes.example - example.meta-scope.cleared-previous-meta-scope.example - string
#   ^^^^^^ string.quoted.single.example - example
#         ^ string.quoted.single.example punctuation.definition.string.end.example - example


```

In Sublime Text, the tests all pass. In syntect 1.2.0, there are some failures - it seems like nested "clear_scopes" are currently unsupported:

```
loading syntax definitions from testdata/Packages/cst/
Testing file testdata/Packages/cst/syntax_test_clear_scopes.txt
The test file references syntax definition file: clear_scopes_test.sublime-syntax
  Assertion selector "source.example example.meta-scope.cleared-previous-meta-scope.example - example.meta-scope.after-clear-scopes.example - example.pushes-clear-scopes - string" from line 8 failed against line 6, column range 10-13 (with text "bar") has scope [<source.example>, <example.meta-scope.cleared-previous-meta-scope.example>, <example.meta-scope.after-clear-scopes.example>, <bar>]
  Assertion selector "example.meta-scope.after-clear-scopes.example example.pops-clear-scopes.example - example.meta-scope.cleared-previous-meta-scope.example - string" from line 10 failed against line 9, column range 2-4 (with text "st") has scope [<source.example>, <example.meta-scope.cleared-previous-meta-scope.example>, <string.quoted.single.example>, <example.pops-clear-scopes.example>]
  Assertion selector "string.quoted.single.example - example" from line 11 failed against line 9, column range 4-10 (with text "ing123") has scope [<source.example>, <example.meta-scope.cleared-previous-meta-scope.example>]
  Assertion selector "string.quoted.single.example punctuation.definition.string.end.example - example" from line 12 failed against line 9, column range 10-11 (with text "\'") has scope [<source.example>, <example.meta-scope.cleared-previous-meta-scope.example>, <punctuation.definition.string.end.example>]
Ok(FailedAssertions(12, 29))
exiting with code 1
```

For a more real-world example, this affects the ASP syntax.
