### ISSUE TITLE
how do I write my own syntax?

### ISSUE THREAD

**Issue by duckfromdiscord** [trishume/syntect#475]
It is not really clear how I can write my own syntaxes start to finish for use with syntect. I have the regexes I need to figure out what needs to be highlighted where, but I do not know how to make these into a `.sublime-syntax` file that will work with syntect. For one thing, I see in the [Sublime docs](http://www.sublimetext.com/docs/syntax.html) that definitions generally look like this:
```yaml
contexts:
  main:
    - match: \b(if|else|for|while)\b
      scope: keyword.control.c
    - match: '"'
      push: string
```
How does syntect know that the `keyword.control.c` scope needs to be highlighted as any color in particular? Does the color theme have some sort of marking for `keyword.control.*` that will highlight any statement with a given `Scope` as long as it starts with `keyword.control.*`?

The docs explain quite well how to load and manipulate syntaxes, but they don't say anything about how to write them.
