### ISSUE TITLE
Incorrect push/pop order when combining meta scopes, content scopes and pushing multiple things

### ISSUE THREAD

**Issue by trishume** [trishume/syntect#51]
This is the bug that is causing at least some, probably most to all of the ASP tests to fail (cc @keith-hall).

The model of the parser outputting only the pushes and pops doesn't hold up to well in some cases. @keith-hall fixed the case of the weird behaviour of `set`, but I found another.

Consider the following section of the ASP syntax:
```yaml
  class_definitions:
    - match: '\b(?i:Class)\s'
      scope: storage.type.asp
      push: [inside_class, class_name]

  class_name:
    - meta_scope: meta.class.asp meta.class.identifier.asp
    # ...
    - match: '{{identifier}}'
      scope: entity.name.class.asp
      pop: true
    # ...

  inside_class:
    - meta_content_scope: meta.class.asp meta.class.body.asp
```

Sublime Text passes the following test:
```asa
' SYNTAX TEST "Packages/ASP/ASP.sublime-syntax"
 Class TestClass2 Public Sub TestSub () Response.Write("wow") End Sub End Class
'^^^^^ meta.class.asp meta.class.identifier.asp storage.type.asp
'      ^ meta.class.asp meta.class.body.asp meta.class.asp meta.class.identifier.asp
'                ^ meta.class.asp meta.class.body.asp
```

Notice how when the `meta_content_scope` of `inside_class` is introduced after `Class`, it is introduced under `meta.class.asp meta.class.identifier.asp`.

`syntect` does not do this. It pushes the `inside_class` `meta_content_scope` on top, but then after `TestClass2` when it pops the `class_name` context it pops 2 scopes, thinking it is popping the `meta_scope` of `class_name`, but actually the `inside_class` scopes are on top of the stack.

I see two ways of approaching this:
- Make pushes like `set` is in [Keith's set branch](https://github.com/forkeith/syntect/tree/set) where they pop the early meta scopes and then re-apply them in the right order.
- Make a breaking change to the API and scrap the idea of the parser outputting operations. Have stacks be linked lists instead of vectors, and have the parser output regions of text with a scope stack, where the scope stacks share tails. Unfortunately this would require a bunch of reference counting. It may be faster, it may be slower, I'm not sure. It would also be a bunch of work.

I'm inclined to take the first route. My worry is that if done simply it will lead to a bunch of redundant popping and pushing the same thing again in the case when only one item is pushed. It's probably a good idea to have a fast path for that case, although it would probably require a bunch more code.

**Comment by trishume** [comment]
I've done some work in [the fix-test-bugs branch](https://github.com/trishume/syntect/compare/fix-test-bugs) that makes things better. It cherry-picks fixes from @keith-hall's `set` branch and then touches them up a bit.

It doesn't fix this issue but it includes the fix to `set` that a fix for this issue could be modeled on.

**Comment by keith-hall** [comment]
I also prefer the first approach because I like the idea of the parser pushing operations :) Nice one for investigating this - I'm glad my branch was helpful.

Is there maybe a potential third option worth considering? When the syntax def is first read, and contains match patterns that push multiple contexts with meta (content) scopes, it could translate/rewrite the contexts so that the existing parser behaviour could remain unchanged. If it would be useful, I can try to come up with an example later of another syntax def (with more contexts) that would have the same meaning and be compatible with syntect as is.

**Comment by trishume** [comment]
^ I pushed a commit that I think fixes this bug to my branch, but I don't know what the performance impact is, and it didn't fix as many tests as I thought.

It fixed one ASP test, and possibly some tests in other languages but there's still lots of other failures.

One thing I'm investigating now is that my model of how the syntax-level scopes are applied is borked.  The ones that are done with things like `scope: text.html.asp` at  the top level. I have them acting like `meta_content_scope`s on the `main` context, but that doesn't seem to be how Sublime does it. I haven't quite figured out what the behaviour is supposed to be yet.

**Comment by keith-hall** [comment]
I think maybe the problem is that the scopes should be rearranged when a context is popped, not just after the match pattern is handled that pushes all the contexts onto the stack in the first place.

Check out the scopes for the following in ST:

```yaml
%YAML 1.2
---
# See http://www.sublimetext.com/docs/3/syntax.html
file_extensions:
  - ec
scope: source.example-push
contexts:
  main:
    - match: 'hello'
      scope: hello
      push: [context1, context2, context3]
  context1:
    - meta_scope: context1
    - meta_content_scope: c1
    - match: \w+
      scope: string
    - match: \.$
      scope: end_c1
      pop: true
  context2:
    - meta_scope: context2
    - meta_content_scope: c2
    - match: \w+
      scope: constant
    - match: \.$
      scope: end_c2
      pop: true
  context3:
    - meta_scope: context3
    - meta_content_scope: c3
    - match: \w+
      scope: comment
    - match: \.$
      scope: end_c3
      pop: true
```

example test text:

```
hello world test foobar.
hello world test foobar.
hello world test foobar.
```

----

I think the top level scope behaviour is that it the scope only applies to the top level syntax. i.e. including or pushing another syntax will never cause that syntax's top level scope to be pushed onto the stack.
