### ISSUE TITLE
CSS: wrong name: `storage.modifier.c++`

### ISSUE THREAD

**Issue by getreu** [trishume/syntect#520]
The generated CSS contains the following:

```css
.storage.modifier.c++ {
 color: #859900;
}
```

which is rejected by Firefox with

    Dangling combinator.  Ruleset ignored due to bad selector.

Is  `+` allowed in identifiers?
