### ISSUE TITLE
Missing Support for Python Console Output and Doctests

### ISSUE THREAD

**Issue by mattharrison** [trishume/syntect#549]
**Description:**
Syntect currently lacks support for highlighting Python console output (characterized by `>>>` and `...` prompts) and doctests. This limitation hinders its ability to accurately represent Python code in various contexts, including code examples, tutorials, and interactive sessions.

**Expected Behavior:**
Syntect should correctly highlight the Python code while ignoring the `>>>`, `...`, and output (stacktrace or stdout).

**Steps to Reproduce:**
1. Create a code snippet containing Python console output or a doctest:

   ```pycon
   >>> print("Hello, world!")
   Hello, world!
   ```

Note this language is commonly called `pycon` (for *py*thon *con*sole), and tools like Pygments or Github markdown support this language (as evident by highlighting the above code).

(My desire it because I'm using Typst and desire to port my books from LaTeX to Typst.)

**Comment by keith-hall** [comment]
I don't know of any `sublime-syntax` files which can currently highlight doctests correctly. Theoretically if we were to create one, it would be a lot easier to extend the base Python sublime-syntax to add support for it, so probably we'd need to wait for https://github.com/trishume/syntect/pull/536 to be merged first

**Comment by mattharrison** [comment]
Where do these syntax definitions live? I poked around a little and
couldn't find them.

**Comment by keith-hall** [comment]
Mainly in the Packages folder/submodule of the testdata folder: https://github.com/trishume/syntect/tree/master/testdata

**Comment by michaelblyons** [comment]
@deathaxe mooted a pycon syntax in ST Discord today:

```yml
%YAML 1.2
---
name: Python (REPL)
scope: source.python.repl
version: 2

extends: Packages/Python/Python.sublime-syntax

contexts:
  main:
    - match: ^>>>
      scope: comment.other.repl
      embed: statements
      escape: ^(?!\.{3})

  comments:
    - meta_prepend: true
    - match: ^\.{3}
      scope: comment.other.repl
```
