### ISSUE TITLE
as_latex_escaped: `_` must be escaped

### ISSUE THREAD

**Issue by LuckyTurtleDev** [trishume/syntect#550]
`_` must be escaped in latex.
I have use the latex example to convert this to latex.
```css
.foo {
    display: flex;
    flex-direction: column;
    align-items: stretch;
    color: black;
}

.novel_mode .foo {
    color: white;
}
```
this generate the following with  `\textcolor[RGB]{121,163,93}{novel_mode } `.
Latex return the following error 
```
\textcolor[RGB]{50,50,50}{.}\textcolor[RGB]{121,163,93}{foo }\textcolor[RGB]{50,50,50}{\{}

\textcolor[RGB]{50,50,50}{    }\textcolor[RGB]{0,179,134}{display}\textcolor[RGB]{50,50,50}{: flex;}

\textcolor[RGB]{50,50,50}{    }\textcolor[RGB]{0,179,134}{flex-direction}\textcolor[RGB]{50,50,50}{: column;}

\textcolor[RGB]{50,50,50}{    }\textcolor[RGB]{0,179,134}{align-items}\textcolor[RGB]{50,50,50}{: stretch;}

\textcolor[RGB]{50,50,50}{    }\textcolor[RGB]{0,179,134}{color}\textcolor[RGB]{50,50,50}{: black;}

\textcolor[RGB]{50,50,50}{\}}

\textcolor[RGB]{50,50,50}{
}

\textcolor[RGB]{50,50,50}{.}\textcolor[RGB]{121,163,93}{novel_mode }\textcolor[RGB]{50,50,50}{.}\textcolor[RGB]{121,163,93}{foo }\textcolor[RGB]{50,50,50}{\{}

\textcolor[RGB]{50,50,50}{    }\textcolor[RGB]{0,179,134}{color}\textcolor[RGB]{50,50,50}{: white;}

\textcolor[RGB]{50,50,50}{\}}
```

Latex return the error `Missing $ inserted`  because `_` should be used in mathmode.
Manual escaping `_` to `/_` fix the issue.
